### ISSUE TITLE
Error: BIDSDataGrabber with pybids >= 0.9

### ISSUE THREAD

**Issue by manikbh** [brainhack-ch/superres-mri#3]
BIDS data grabber does not work with pybids >= 0.9:

Jupyter Notebook  error:
------------------------------------------------
```
191108-16:17:18,426 nipype.workflow INFO:
	 Workflow bids_demo settings: ['check', 'execution', 'logging', 'monitoring']
191108-16:17:18,441 nipype.workflow INFO:
	 Running serially.
191108-16:17:18,446 nipype.workflow INFO:
	 [Node] Setting-up "bids_demo.bids_grabber" in "/home/brainhacker/data/derivatives/mialsrtk/bids_demo/bids_grabber".
191108-16:17:18,450 nipype.workflow INFO:
	 [Node] Running "bids_grabber" ("nipype.interfaces.io.BIDSDataGrabber")
191108-16:17:18,899 nipype.workflow WARNING:
	 Storing result file without outputs
191108-16:17:18,901 nipype.workflow WARNING:
	 [Node] Error on "bids_demo.bids_grabber" (/home/brainhacker/data/derivatives/mialsrtk/bids_demo/bids_grabber)
191108-16:17:18,903 nipype.workflow ERROR:
	 Node bids_grabber failed to run on host bh-p05-03.
191108-16:17:18,903 nipype.workflow ERROR:
	 Saving crash info to /home/brainhacker/superres-mri/notebooks/crash-20191108-161718-brainhacker-bids_grabber-2e444a58-15b6-4bc4-b0c8-a98a3b1476bb.pklz
Traceback (most recent call last):
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 48, in run
    node.run(updatehash=updatehash)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 569, in _run_interface
    return self._run_command(execute)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 384, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/interfaces/io.py", line 2836, in _list_outputs
    derivatives=self.inputs.index_derivatives)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/bids/layout/layout.py", line 226, in __init__
    index_metadata=index_metadata)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/bids/layout/layout.py", line 556, in add_derivatives
    self.derivatives[pipeline_name] = BIDSLayout(deriv, **kwargs)
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/bids/layout/layout.py", line 211, in __init__
    indexer.index_metadata()
  File "/home/brainhacker/miniconda3/envs/supermri-env/lib/python3.7/site-packages/bids/layout/index.py", line 284, in index_metadata
    file_md.update(pl)
ValueError: dictionary update sequence element #0 has length 4; 2 is required

191108-16:17:18,905 nipype.workflow INFO:
	 ***********************************
191108-16:17:18,905 nipype.workflow ERROR:
	 could not run node: bids_demo.bids_grabber
191108-16:17:18,906 nipype.workflow INFO:
	 crashfile: /home/brainhacker/superres-mri/notebooks/crash-20191108-161718-brainhacker-bids_grabber-2e444a58-15b6-4bc4-b0c8-a98a3b1476bb.pklz
191108-16:17:18,907 nipype.workflow INFO:
	 ***********************************
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-288982abd1f9> in <module>
     68 
     69 wf.connect(preparePaths, "docker_T2ws_paths", nlmDenoise, "input_images")
---> 70 res = wf.run()

~/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py in run(self, plugin, plugin_args, updatehash)
    597         if str2bool(self.config['execution']['create_report']):
    598             self._write_report_info(self.base_dir, self.name, execgraph)
--> 599         runner.run(execgraph, updatehash=updatehash, config=self.config)
    600         datestr = datetime.utcnow().strftime('%Y%m%dT%H%M%S')
    601         if str2bool(self.config['execution']['write_provenance']):

~/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py in run(self, graph, config, updatehash)
     69 
     70         os.chdir(old_wd)  # Return wherever we were before
---> 71         report_nodes_not_run(notrun)

~/miniconda3/envs/supermri-env/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py in report_nodes_not_run(notrun)
     93                 logger.debug(subnode._id)
     94         logger.info("***********************************")
---> 95         raise RuntimeError(('Workflow did not execute cleanly. '
     96                             'Check log for details'))
     97 

RuntimeError: Workflow did not execute cleanly. Check log for details
```

**Comment by manikbh** [comment]
This is probably due to changes in bids layout API as [documented here](https://github.com/bids-standard/pybids/blob/master/CHANGELOG.md#version-090-may-21-2019).
Notably 

> BIDSLayout.get_metadata() no longer takes additional entities as optional keyword arguments (they weren't necessary for anything).
